### ISSUE TITLE
Spec stages vs Community Spec governance

### ISSUE THREAD

**Issue by lehors** [slsa-framework/governance#20]
It was pointed out that we need to make sure we follow the [Community Specification protocol](https://github.com/slsa-framework/governance/blob/main/5._Governance.md#4-specification-development-process) which governs the SLSA spec work.

It refers to "Draft Specification", "Candidate for Approved Specification", and "Approved Specification".

We can either indicate how the "working draft", "in review", and "stable" states we are currently using map to those - thankfully it's a simple one to one mapping so it's easy enough to do, or switch and use the above names instead.

What should we do?

I think specifying the mapping on the spec stages page is the easier way to go.

**Comment by lehors** [comment]
I should point out that this has implications from a licensing obligations point of view. Because of that, although I find it tempting to just change to using the governance names this would mean that we relabel the 0.1 spec as an "Approved Specification". Yet, this doesn't seem quite right given that it wasn't developed within the Community Specification framework.

The publication of an "Approved Specification" needs to be clearly stated because it has implications as to whether contributors can exclude any relevant IP from their licensing obligations...

**Comment by MarkLodato** [comment]
My inclination is to call v0.1 an "Approved Specification", but we should confirm with OpenSSF/LF.

Note that:

- The [Community Specification license](https://github.com/slsa-framework/governance/blob/main/1._Community_Specification_License-v1.md) does not define "candidate" at all, just "draft" and "approved". The "candidate" is part of SLSA's [governance](https://github.com/slsa-framework/governance/blob/main/5._Governance.md) document, which we could change.
- Also, we perhaps should differentiate between a "release candidate snapshot" (`/v1.0-rc1`) and the working draft of the candidate (`/v1.0`). Right now we are calling the former "in review" and the latter "working draft", which seems to conflict with the notion of a "candidate for approved specification".

I suggest that we use a single set of terminology (rather than creating a mapping), and that single set be defined in the governance repo. So:
- Move https://slsa.dev/spec-stages to the governance repo (and add a redirect and update links).
- Rename the stages to align with the Community Specification. Proposal:
  - Working Draft - keep
  - In review - rename to "Release Candidate" and say that it's still a "draft" according to the license. (Still not sure how to resolve the "snapshot vs draft of candidate" issue.)
  - Stable - rename to "Approved"
- Update the governance repo and slsa.dev to use the new terminology consistently.

What do you think?

**Comment by lehors** [comment]
You're right that the license does not define "candidate" but the [governance doc](https://github.com/slsa-framework/governance/blob/main/5._Governance.md#4-specification-development-process) reads:

_the applicable Maintainers will Approve that Draft Specification as a candidate for "Approved Specification" status._

and:

_The Maintainers will state in the distribution that the Draft Specification is a candidate for "Approved Specification" status, and will announce the start of a two-week review period (the "Review Period")._

So we need to be diligent about communicating when a specification becomes a candidate for "Approved Specification" status at least 2 weeks prior to doing so and if we don't communicate this by defining a specification stage for it we'll need to add it in text somewhere.

I agree that it would be desirable to just use one set of terms rather than 2. Thankfully none of this actually requires any changes to our current workflow. This is how the two map:

Working Draft -> Draft Specification
In Review -> Candidate for Approved Specification
Stable -> Approved Specification
Retired -> X - not sure what that would be but we can probably just keep it as is

But I don't think we want to use "Candidate for Approved Specification" in the UI, this is awfully long and would screw up the page layout! I would suggest we use something like:

Draft, In Review, Approved, and Retired.

That would I think align the two.

We can move the page into this repo if you want but then when people follow the link from the Status field in the spec it will take them onto github out of the slsa.dev site. For this reason I would rather keep it within the website which gives a nicer UX.

**Comment by MarkLodato** [comment]
@lehors and I discussed and agreed on "Draft, Candidate, Approved, Retired".

**Comment by MarkLodato** [comment]
Is this done now?

**Comment by lehors** [comment]
Yes, indeed. Closing.
